version: '3'

services:
  db:
    image: postgres:10.1-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
  web:
    build: .
    command: gunicorn storemgmt.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - .:/code
      - DataVolume2:/code/staticfiles
    ports:
      - 8000
    depends_on:
      - db

volumes:
  postgres_data:
  DataVolume2:
    external: true